/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lcyKaPgFbUx
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

export function Navbar() {
  return (
    <header className="bg-gray-900 text-white py-4 px-6 md:px-8 lg:px-10 flex items-center justify-between border border-white rounded-sm">
      <div className="flex items-center gap-4">
        <a
          href="/"
          className="bg-gray-800 rounded-md px-3 py-1 text-sm font-medium"
        >
          TalkTrain
        </a>
      </div>
      <a
        target="none"
        href="https://satyam-x10.github.io/portfolio/"
        className="flex items-center gap-4"
      >
        About Developer
      </a>
    </header>
  );
}
