/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/clngADT0wNa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Separator } from "@/components/ui/separator"
import { Checkbox } from "@/components/ui/checkbox"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function ter() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-gray-900 text-white p-4 flex items-center justify-between">
        <h1 className="text-xl font-bold">Conversations</h1>
        <div className="flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="icon" variant="ghost">
                <FilterIcon className="h-6 w-6" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="w-64 p-4 space-y-2">
              <DropdownMenuLabel>Filter by</DropdownMenuLabel>
              <Separator />
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Active</span>
                  <Checkbox defaultChecked id="filter-active" />
                </div>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Archived</span>
                  <Checkbox id="filter-archived" />
                </div>
              </DropdownMenuCheckboxItem>
              <Separator />
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Today</span>
                  <Checkbox defaultChecked id="filter-today" />
                </div>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Last Week</span>
                  <Checkbox id="filter-last-week" />
                </div>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Last Month</span>
                  <Checkbox id="filter-last-month" />
                </div>
              </DropdownMenuCheckboxItem>
              <Separator />
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Individual</span>
                  <Checkbox defaultChecked id="filter-individual" />
                </div>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <div className="flex items-center justify-between">
                  <span>Group</span>
                  <Checkbox id="filter-group" />
                </div>
              </DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex-1 overflow-y-auto">
        <div className="p-4 space-y-4">
          <div className="flex items-center gap-4 bg-gray-100 p-4 rounded-lg dark:bg-gray-800">
            <Avatar>
              <AvatarImage alt="John Doe" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h3 className="font-semibold">John Doe</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-1">Hey, how's it going?</p>
            </div>
            <span className="text-gray-500 dark:text-gray-400 text-sm">10:30 AM</span>
          </div>
          <div className="flex items-center gap-4 bg-gray-100 p-4 rounded-lg dark:bg-gray-800">
            <Avatar>
              <AvatarImage alt="Jane Smith" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JS</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h3 className="font-semibold">Jane Smith</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-1">Can we schedule a call?</p>
            </div>
            <span className="text-gray-500 dark:text-gray-400 text-sm">Yesterday</span>
          </div>
          <div className="flex items-center gap-4 bg-gray-100 p-4 rounded-lg dark:bg-gray-800">
            <Avatar>
              <AvatarImage alt="Group Chat" src="/placeholder-avatar.jpg" />
              <AvatarFallback>GC</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h3 className="font-semibold">Design Team</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-1">Don't forget the design review tomorrow.</p>
            </div>
            <span className="text-gray-500 dark:text-gray-400 text-sm">2 days ago</span>
          </div>
        </div>
      </div>
    </div>
  )
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}
