/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YUJNcOxk8h6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "../ui/button"

export function Typebar() {
  return (
    <div className="flex flex-row items-center justify-around space-x-2 space-y-2 m-2 p-2 fixed bottom-0 w-[95vw]">
      <Input
        className="border-2 flex-1 border-gray-300 focus:border-blue-500 transition-colors duration-200"
        id="text-input"
        placeholder="Type here..."
        type="text"
      />
      <Button className="bg-blue-500 text-white mx-1 px-2 py-1 rounded">Send</Button>
    </div>

  )
}
